//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 產生的 Include 檔案。
// 由 game.rc 使用
//
#define IDD_ABOUTBOX                    100
#define IDP_SOCKETS_INIT_FAILED         104
#define IDR_MAINFRAME                   128
#define IDR_GAMETYPE                    129
#define IDB_BALL                        130
#define IDB_RACKET                      131
#define IDB_ERASER1                     131
#define IDB_BITMAP1                     132
#define IDB_BACKGROUND                  132
#define IDB_CORNER                      133
#define IDB_BALL1                       134
#define IDB_BALL2                       135
#define IDB_BALL3                       136
#define IDB_BALL4                       137
#define IDB_0                           138
#define IDB_1                           139
#define IDB_2                           140
#define IDB_3                           141
#define IDB_4                           142
#define IDB_5                           143
#define IDB_6                           144
#define IDB_7                           145
#define IDB_8                           146
#define IDB_9                           147
#define IDB_MINUS                       148
#define IDB_CENTER                      149
#define IDB_ERASER2                     150
#define IDB_ERASER3                     151
#define IDB_CONTINUE                    152
#define IDC_GAMECURSOR                  153
#define IDB_HELP                        155
#define IDB_BITMAP2                     156
#define IDB_LOADING                     156
#define IDB_TEST_GRASS                  161
#define IDB_TEST_ROCK                   162
#define IDB_TEST                        164
#define IDB_DOG                         167
#define IDB_WITCH                       173
#define IDB_WITCH_BACK                  174
#define IDB_GRASS                       175
#define IDB_BUSH                        176
#define IDB_HOUSE_1                     179
#define IDB_HOUSE_2                     180
#define IDB_HOUSE_3                     181
#define IDB_HOUSE_4                     182
#define IDB_HOUSE_5                     183
#define IDB_HOUSE_6                     184
#define IDB_HOUSE_7                     185
#define IDB_HOUSE_8                     186
#define IDB_HOUSE_9                     187
#define IDB_HOUSE_10                    188
#define IDB_HOUSE_11                    189
#define IDB_HOUSE_12                    190
#define IDB_HOUSE_13                    191
#define IDB_HOUSE_14                    192
#define IDB_HOUSE_15                    193
#define IDB_HOUSE_16                    194
#define IDB_HOUSE_17                    195
#define IDB_HOUSE_18                    196
#define IDB_HOUSE_19                    197
#define IDB_HOUSE_20                    198
#define IDB_HOUSE_21                    199
#define IDB_HOUSE_22                    200
#define IDB_HOUSE_23                    204
#define IDB_HOUSE_24                    205
#define IDB_HOUSE_25                    206
#define IDB_SHOP_BACKGROUND             208
#define IDB_LEFT_ARROW                  209
#define IDB_ANNOUNCEMENT                211
#define IDB_SIGN                        212
#define IDB_OPPONENT_SCENT              214
#define IDB_BATTLE_BACKGROUND_1         215
#define IDB_BATTLE_BACKGROUND_2         216
#define IDB_BATTLE_BACKGROUND_3         218
#define IDB_BLANK                       219
#define IDB_ROCK                        220
#define IDB_KIRBY                       221
#define IDB_KIRBY_ANGRY                 222
#define IDB_TEST_WEAPON                 223
#define IDB_KIRBY_WOUNDED               224
#define IDB_RF_KIRBY                    225
#define IDB_RF_KIRBY_WOUNDED            226
#define IDB_RF_KIRBY_ANGRY              227
#define IDB_KIRBY_UNDER_ATTACK          228
#define IDB_RF_KIRBY_UNDER_ATTACK       229
#define IDB_CHARACTER_1                 230
#define IDB_CHARACTER_2                 231
#define IDB_CHARACTER_3                 232
#define IDB_CHARACTER_4                 233
#define IDB_CHARACTER_5                 234
#define IDB_CHARACTER_6                 235
#define IDB_RF_CHARACTER_1              236
#define IDB_RF_CHARACTER_2              237
#define IDB_RF_CHARACTER_3              238
#define IDB_RF_CHARACTER_4              239
#define IDB_RF_CHARACTER_5              240
#define IDB_RF_CHARACTER_6              241
#define IDB_HEALTHBAR_BACKGROUND        242
#define IDB_HEALTHBAR                   243
#define IDB_BITMAP3                     245
#define IDB_DOT                         245
#define IDB_ENERGY_0                    246
#define IDB_ENERGY_1                    247
#define IDB_ENERGY_2                    248
#define IDB_ENERGY_3                    249
#define IDB_ENERGY_4                    250
#define IDB_ENERGY_5                    251
#define IDB_ENERGY_6                    252
#define IDB_ENERGY_7                    253
#define IDB_ENERGY_8                    254
#define IDB_RF_ENERGY_0                 255
#define IDB_RF_ENERGY_1                 258
#define IDB_RF_ENERGY_2                 259
#define IDB_RF_ENERGY_3                 260
#define IDB_RF_ENERGY_4                 261
#define IDB_RF_ENERGY_5                 262
#define IDB_RF_ENERGY_6                 263
#define IDB_RF_ENERGY_7                 264
#define IDB_BITMAP5                     265
#define IDB_RF_ENERGY_8                 265
#define IDB_CLERK                       266
#define IDB_STORE_PAD                   267
#define IDB_BITMAP4                     268
#define IDB_U                           268
#define IDC_README                      1001
#define ID_FILE_PAUSE                   32771
#define ID_TOGGLE_FULLSCREEN            32772
#define ID_BUTTON_FULLSCREEN            32773
#define ID_BUTTON_PAUSE                 32774
#define ID_BUTTON_UNITTEST              32775

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        269
#define _APS_NEXT_COMMAND_VALUE         32776
#define _APS_NEXT_CONTROL_VALUE         1003
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
